api_version: '0.1'
env: flex

runtime_config:  
  jdk: openjdk8
  server: tomcat8 # Run on Tomcat8

manual_scaling:
  instances: 1
  

handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1